# Generated by Django 4.0.4 on 2022-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_blogpost_description_alter_blogpost_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
